
create TABLE IF NOT EXISTS users (
    id int generated by default as identity PRIMARY KEY,
    name varchar(50) NOT NULL,
    email varchar   NOT NULL UNIQUE
);

create TABLE IF NOT EXISTS items (
    id int generated by default as identity PRIMARY KEY,
    name varchar(50) NOT NULL,
    description varchar(300)   NOT NULL,
    owner_id int   NOT NULL,
    available boolean NOT NULL,
    request int,
    CONSTRAINT fk_items_owner_id FOREIGN KEY(owner_id) REFERENCES users (id)
);

create type IF NOT EXISTS booking_status as ENUM ('WAITING', 'APPROVED', 'REJECTED');

CREATE TABLE IF NOT EXISTS bookings (
    id int generated by default as identity PRIMARY KEY,
    start_time timestamp without time zone NOT NULL,
    end_time timestamp without time zone NOT NULL,
    item_id int   NOT NULL,
    booker_id int   NOT NULL,
    status booking_status,
    CONSTRAINT fk_bookings_item_id FOREIGN KEY(item_id) REFERENCES items (id),
    CONSTRAINT fk_bookings_booker_id FOREIGN KEY(booker_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS comments (
    id int generated by default as identity PRIMARY KEY,
    text varchar(500) NOT NULL,
    item_id int   NOT NULL,
    author_id int   NOT NULL,
    created timestamp without time zone,
    CONSTRAINT fk_comments_item_id FOREIGN KEY(item_id) REFERENCES items (id),
    CONSTRAINT fk_comments_author_id FOREIGN KEY(author_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS requests (
    id int generated by default as identity PRIMARY KEY,
    description varchar(500) NOT NULL,
    requestor_id int   NOT NULL,
    created timestamp without time zone,
    CONSTRAINT fk_requests_requestor_id FOREIGN KEY(requestor_id) REFERENCES users (id)
);