
CREATE TABLE IF NOT EXISTS users (
    id long generated by default as identity PRIMARY KEY,
    name varchar(50) NOT NULL,
    email varchar   NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
    id long generated by default as identity PRIMARY KEY,
    name varchar(50) NOT NULL,
    description varchar(300)   NOT NULL,
    owner long   NOT NULL,
    available boolean NOT NULL,
    request long,
    CONSTRAINT fk_Film_Rating_id FOREIGN KEY(owner) REFERENCES users (id)
);


--create unique index IF NOT EXISTS "USER_EMAIL_UINDEX" ON "User" ("Email");
--create unique index IF NOT EXISTS "USER_LOGIN_UINDEX" ON "User" ("Login");


